# To update the pods, use
#   pod install 
# 

inhibit_all_warnings!

workspace 'PageKiteApp'
xcodeproj 'PageKite/PageKite.xcodeproj'

platform :osx, '10.7'
pod 'GCDWebServer', '~> 2.4'
pod 'FXKeychain',   '~> 1.5'
pod 'PageKiteKit', :podspec => 'https://raw.githubusercontent.com/jaylyerly/libpagekite/master/mac/PageKiteDemo/PageKiteKit.podspec'
#pod 'PageKiteKit', :path => '~/git/libpagekite/mac/PageKiteDemo'

