# To update the pods, use
#   pod install 
# 

workspace 'PageKiteApp'
xcodeproj 'PageKite/PageKite.xcodeproj'

platform :osx, '10.7'
pod 'GCDWebServer', '~> 2.4', :inhibit_warnings => true
pod 'FXKeychain',   '~> 1.5', :inhibit_warnings => true
pod 'PageKiteKit', :podspec => 'https://raw.githubusercontent.com/jaylyerly/libpagekite/master/mac/PageKiteDemo/PageKiteKit.podspec'

