# To update the pods, use
#   pod install 
# 

workspace 'PageKiteDemo'

#link_with 'PageKiteDemo', 'PocketPageKiteDemo', 'PageKiteKit', 'PageKiteKitIOS'

target :PageKiteDemo, :exclusive => true do
  xcodeproj 'PageKiteDemo'
  platform :osx, '10.7'
  pod 'GCDWebServer',       '~> 2.4',    :inhibit_warnings => true
end

target :PageKiteKit, :exclusive => true do
  xcodeproj '../PageKiteKit/PageKiteKit'
  platform :osx, '10.7'
  pod 'xmlrpc',             '~> 2.3.3',  :inhibit_warnings => true
  pod 'libev',              '~> 4.15.0', :inhibit_warnings => true
end

target :PocketPageKiteDemo, :exclusive => true do
  xcodeproj 'PageKiteDemo'
  platform :ios, '7.0'
  pod 'GCDWebServer',           '~> 2.4',    :inhibit_warnings => true
  pod "RMPickerViewController", "~> 1.1.1",  :inhibit_warnings => true
  pod "NYXImagesKit",           "~> 2.3",    :inhibit_warnings => true
end

target :PageKiteKitIOS, :exclusive => true do
  xcodeproj '../PageKiteKit/PageKiteKit'
  platform :ios, '6.0'
  pod 'xmlrpc',             '~> 2.3.3',  :inhibit_warnings => true
  pod 'OpenSSL',            '~> 1.0.1',  :inhibit_warnings => true
  pod 'libev',              '~> 4.15.0', :inhibit_warnings => true
end

